django_shop/accounts/urls.py
from django.urls import path, include
from . import views


app_name = 'accounts'

urlpatterns = [
    path('profile/', views.profile_view, name='profile'),
    path('edit/<int:pk>', views.profile_edit, name='edit'),
    path('signup/', views.sign_up, name='signup'),
    path('', include('django.contrib.auth.urls'))
]

django_shop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('order/', views.oder_summary, name='order'),
    path('create_order/<int:pk>', views.create_order, name='create_order'),
    path('complete/', views.complete, name='complete'),
    path('add/<int:pk>', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:pk>', views.remove_from_cart, name='remove_from_cart'),
]

django_shop/catalog/urls.py
from django.urls import path
from . import views

app_name = 'catalog'

urlpatterns = [
    path('', views.categories_list, name='categories'),
    path('<slug>/', views.product_list, name='products'),
    path('<category_slug>/<int:pk>/', views.product_detail, name='product'),
]

django_shop/django_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('catalog.urls', namespace='catalog')),
    path('cart/', include('cart.urls', namespace='cart')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_shop/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumber
from django.urls import reverse
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.utils.timezone import timezone


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=20, blank=True)
    user_pic = models.ImageField(blank=True)
    email = models.EmailField(blank=True)
    phone_number = PhoneNumber()
    address = models.CharField(max_length=200)
    birthday = models.DateField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{}\'s profile.'.format(self.user.username)

    def get_absolute_url(self):
        return reverse('accounts:profile', args=[self.pk])

    def get_completed_orders(self):
        completed = self.orders.filter(ordered=True)
        return completed

    def get_pending_orders(self):
        pending = self.orders.filter(ordered=False)
        return pending

    def edit_profile(self):
        return reverse('accounts:edit', args=[self.pk])


@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()


post_save.connect(create_profile, sender=User)

django_shop/accounts/forms.py
from django.forms import ModelForm
from .models import Profile
from phonenumber_field.modelfields import PhoneNumber


class ProfileForm(ModelForm):

    class Meta:
        model = Profile
        fields = ('name', 'user_pic', 'email', 'birthday')
        labels = {
            'name': 'ФИО',
            'user_pic': 'Фото',
            'email': 'Электронная почта',
            'birthday': 'Дата рождения',
        }

django_shop/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from .forms import ProfileForm
from .models import Profile
from functools import wraps
from django.http import HttpResponseRedirect
from django_shop.utils import ssl_redirect


def sign_up(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            raw_password = form.cleaned_data['password1']
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('accounts:profile')
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form':form})


@login_required
def profile_view(request):
    profile = get_object_or_404(Profile, pk=request.user.pk)
    return render(request, 'accounts/profile.html', {'profile': profile})

# @ssl_redirect
@login_required
def profile_edit(request, pk):
    profile = get_object_or_404(Profile, pk=pk)
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('accounts:profile')
    else:
        form = ProfileForm(initial={
            'name': profile.name,
            'email': profile.email,
            'birthday': profile.birthday,
        })
    return render(request, 'accounts/edit_profile.html', {'form': form})


def ssl_redirect_land(request):
    return redirect('profile')


def http_redirect_land(request):
    return redirect('catalog')

django_shop/accounts/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Магазин</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>

<div class="container-fluid">

<div class="row">
  <div class="col-sm-2">
  {% block sidebar %}
  <ul class="sidebar-nav">
    <li><a href="{% url 'catalog:categories' %}">Категории товаров</a></li>
    <li><a href="{% url 'accounts:profile' %}">Профиль</a></li>
  </ul>

  <ul class="sidebar-nav">
   {% if user.is_authenticated %}
     <li>User: {{ user.get_username }}</li>
     <li><a href="{% url 'accounts:logout' %}">Выйти</a></li>
   {% else %}
     <li><a href="{% url 'accounts:login' %}">Войти</a></li>
   {% endif %}
  </ul>

{% endblock %}

  </div>
  <div class="col-sm-10 ">
  {% block content %}{% endblock %}


  </div>
</div>

</div>
</body>
</html>