django_shop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('order/', views.oder_summary, name='order'),
    path('create_order/<int:pk>', views.create_order, name='create_order'),
    path('complete/', views.complete, name='complete'),
    path('add/<int:pk>', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:pk>', views.remove_from_cart, name='remove_from_cart'),
]

django_shop/catalog/urls.py
from django.urls import path
from . import views

app_name = 'catalog'

urlpatterns = [
    path('', views.categories_list, name='categories'),
    path('<slug>/', views.product_list, name='products'),
    path('<category_slug>/<int:pk>/', views.product_detail, name='product'),
]

django_shop/django_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('catalog.urls', namespace='catalog')),
    path('cart/', include('cart.urls', namespace='cart')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_shop/catalog/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):

    CHOICES = (
        ('Одежда и обувь', 'Одежда и обувь'),
        ('Бытовая техника', 'Бытовая техника'),
        ('Строительный инвентарь', 'Строительный инвентарь'),
        ('Медицинские товары', 'Медицинские товары'),
    )

    title = models.CharField(choices=CHOICES, max_length=100)
    slug = models.SlugField()

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('catalog:category', kwargs=[self.slug])

    def get_product_list(self):
        products = [product for product in self.products.all()]
        return products


class Product(models.Model):
    category = models.ForeignKey(Category,
                                 on_delete=models.CASCADE, related_name='products')
    title = models.CharField(max_length=20)
    price = models.FloatField()
    product_pic = models.ImageField()
    description = models.CharField(max_length=200)
    added = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('catalog:product', kwargs={'category_slug': self.category.slug,
                                                  'pk': self.pk})

    def add_to_cart(self):
        return reverse('cart:add_to_cart', args=[self.pk])

    def remove_from_cart(self):
        return reverse('cart:remove_from_cart', args=[self.pk])

django_shop/catalog/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from .models import Category, Product
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django_shop.utils import ssl_redirect

# @ssl_redirect
def categories_list(request):
    # import pprint
    # pprint.pprint(request.META)
    categories = Category.objects.all()
    context = {'categories': categories}
    return render(request, 'catalog/categories_list.html', context)


def product_list(request, slug):

    category = get_object_or_404(Category, slug=slug)
    products_list = category.products.all()
    page = request.GET.get('page', '1')
    paginator = Paginator(products_list, 3)
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    context = {'products': products}
    return render(request, 'catalog/product_list.html', context)


def product_detail(request, category_slug, pk):
    product = get_object_or_404(Product, pk=pk)
    context = {'product': product}
    return render(request, 'catalog/product_detail.html', context)

django_shop/catalog/templates/catalog/categories_list.html
{% extends "base.html" %}

{% block content %}
    <h1>Каталог</h1>

    {% if categories %}
    <ul>

      {% for category in categories %}
      <li>
        <a href="{% url 'catalog:products' category.slug %}">{{ category.get_title_display }}</a>
      </li>
      {% endfor %}

    </ul>

    {% else %}
      <p>Категории пока не добавлены.</p>
    {% endif %}
{% endblock %}

django_shop/catalog/templates/catalog/product_detail.html
{% extends "base.html" %}

{% block content %}

<h4>{{ product.title }}</h4>


<p><strong>Категория:</strong>
    <a href="{% url 'catalog:products' product.category.slug %}">
    {{ product.category.title }}
    </a>
</p>
<p><strong>Цена:</strong> {{ product.price }} --
<a href="{{ product.add_to_cart }}" type="button">Добавить в корзину.</a></p>
<p><img src="{{ product.product_pic.url }}" alt="No image" style="width:100px;height:110px;"></p>
<p><strong>Описание:</strong> {{ product.description }}</p>


{% endblock %}

django_shop/catalog/templates/catalog/product_list.html
{% extends "base.html" %}

{% block content %}
    <h1>Каталог</h1>

    {% if products %}
    <ul>

     {% for product in products %}
      <li>
        <a href="{{ product.get_absolute_url }}">{{ product.title }}</a> --
        <a href="{{ product.add_to_cart }}" type="button">Добавить в корзину.</a>
        <p>{{ product.price }}</p>
        <p><img src="{{ product.product_pic.url }}" alt="No image" style="width:100px;height:110px;"></p>
      </li>
      {% endfor %}

    </ul>

    {% else %}
      <p>Товары пока не добавлены.</p>
    {% endif %}

{% block pagination %}
    {# if is_paginated #}
        <div class="pagination">
            <span class="page-links">
                {% if products.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ products.number }} of {{ products.paginator.num_pages }}.
                </span>
                {% if products.has_next %}
                    <a href="{{ request.path }}?page={{ products.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {# endif #}
  {% endblock %}

{% endblock %}